### ISSUE TITLE
what's best practice for micro frontend import error on shell?

### ISSUE THREAD

**Issue by muhammetbilgin** [afonsojramos/astro-microfrontends#1]
Hi, firstly thanks for this example. How can i handle error and suspense for micro frontend on shell app? 

![image](https://github.com/afonsojramos/astro-microfrontends/assets/72626321/5589e1d5-a42e-463a-9b3a-b6e68703e8b7)

I tried simple catch scenario but it's not look like smart way.

`try {
    const { MicroFrontendB } = await import('http://localhost:7200/bundle.js').catch(reason => { })
    if (MicroFrontendB) {
      console.log(MicroFrontendB);
    }
  }
  catch (error) {
    console.log('error');
  }`

**Comment by afonsojramos** [comment]
Hi! I would say that the best way to do it would be with an Error Boundary, however, Astro doesn't really support that, so you probably will need to add some Astro middleware to do it.
