### ISSUE TITLE
State management issue

### ISSUE THREAD

**Issue by muhammetbilgin** [afonsojramos/astro-microfrontends#2]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Hi,

i have issue with this scenerio with zustand. Also tried with redux but i got some error. 

Alternatively work with module federation plugin, states works with that way but css inject not working.

Any idea or scenerio for remote states or global states ? 

![image](https://github.com/afonsojramos/astro-microfrontends/assets/72626321/7d395fa0-36d8-455e-a592-7120314364d6)

**Zustand store:**
```ts import { create } from 'zustand';

type Store = {
  count: number;
  inc: () => void;
};

export const useStore = create<Store>()((set) => ({
  count: 1,
  inc: () => set((state) => ({ count: state.count + 1 })),
}));
```

**App.tsx:**
```tsx
import { useStore } from './store/store';
import './index.css';

function App() {
  const { count, inc } = useStore();
  return (
    <>
      <h1 className="text-red-500 text-xl font-semibold">test tailwind</h1>
      <span>{count}</span>
      <button onClick={inc}>one up</button>
    </>
  );
}

export default App;
````

**vite.config.ts**
```js 
 build: {
    rollupOptions: {
      input: resolve(__dirname, 'src/App.tsx'),
      preserveEntrySignatures: 'exports-only',
      external: ['react', 'react-dom'],
      output: {
        entryFileNames: 'kiosksBundle.js',
        format: 'esm',
      },
    },
  },
```

Shell side React remote component
```tsx 

export default function ReactComponentB() {
  const MyDynamicComponent = React.lazy(() => import('http://localhost:7100/kiosksBundle.js'));
  return (
    <ErrorBoundary>
      <React.Suspense
        fallback={<div className="h-96 w-96 bg-gray-300/50 rounded-xl animate-pulse" />}
      >
        <MyDynamicComponent />
      </React.Suspense>
    </ErrorBoundary>
  );
}

```

### 🪜 Steps To Reproduce

1.Add zustand to remote app
2.Create simple store and counter
3.Build & serve remote app
4.Build & serve shell app

### ℹ System Info

```Markdown
Edition	Windows 10 Pro
Version	22H2
Installed on	‎1/‎11/‎2024
OS build	19045.4291
Experience	Windows Feature Experience Pack 1000.19056.1000.0
```

**Comment by afonsojramos** [comment]
Honestly, I have no idea, and this repo was just a demo, so I don't think I can help much, sorry!
